AWSTemplateFormatVersion: '2010-09-09'
Description: Dynamic DNS updater with Lambda - just curl a URL to update your DNS

Parameters:
  RecordName:
    Type: String
    Description: Full DNS record to update (e.g., home.example.com)

Resources:
  # Setup: generate auth token and find hosted zone
  SetupFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-setup'
      Runtime: python3.12
      Handler: index.handler
      Timeout: 10
      Role: !GetAtt SetupRole.Arn
      Tags:
        - Key: Project
          Value: aws-easy
        - Key: Template
          Value: dynamic-dns
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import secrets

          def handler(event, context):
              if event['RequestType'] == 'Delete':
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                  return

              # Generate or preserve token
              if event['RequestType'] == 'Update':
                  token = event.get('OldResourceProperties', {}).get('Token', '')
                  if not token:
                      token = secrets.token_urlsafe(24)
              else:
                  token = secrets.token_urlsafe(24)

              # Find hosted zone
              record_name = event['ResourceProperties']['RecordName'].rstrip('.')
              route53 = boto3.client('route53')

              parts = record_name.split('.')
              for i in range(len(parts) - 1):
                  domain = '.'.join(parts[i:]) + '.'
                  zones = route53.list_hosted_zones_by_name(DNSName=domain, MaxItems='1')
                  for zone in zones.get('HostedZones', []):
                      if zone['Name'] == domain:
                          zone_id = zone['Id'].replace('/hostedzone/', '')
                          cfnresponse.send(event, context, cfnresponse.SUCCESS, {
                              'Token': token,
                              'ZoneId': zone_id
                          })
                          return

              cfnresponse.send(event, context, cfnresponse.FAILED, {}, reason=f'No hosted zone found for {record_name}')

  SetupRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Project
          Value: aws-easy
        - Key: Template
          Value: dynamic-dns
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ListHostedZones
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: route53:ListHostedZonesByName
                Resource: '*'

  Setup:
    Type: Custom::Setup
    Properties:
      ServiceToken: !GetAtt SetupFunction.Arn
      RecordName: !Ref RecordName

  # Lambda function to update DNS
  UpdateFunction:
    Type: AWS::Lambda::Function
    DependsOn: UpdateFunctionLogGroup
    Properties:
      FunctionName: !Sub '${AWS::StackName}-updater'
      Runtime: python3.12
      Handler: index.handler
      Timeout: 10
      Role: !GetAtt LambdaRole.Arn
      Tags:
        - Key: Project
          Value: aws-easy
        - Key: Template
          Value: dynamic-dns
      Environment:
        Variables:
          HOSTED_ZONE_ID: !GetAtt Setup.ZoneId
          RECORD_NAME: !Ref RecordName
          AUTH_TOKEN: !GetAtt Setup.Token
      Code:
        ZipFile: |
          import boto3
          import json
          import os

          def handler(event, context):
              source_ip = event['requestContext']['http']['sourceIp']
              path_token = event.get('pathParameters', {}).get('token', '')

              # Validate token
              if path_token != os.environ['AUTH_TOKEN']:
                  print(f"AUTH_FAILED ip={source_ip}")
                  return {
                      'statusCode': 403,
                      'body': json.dumps({'error': 'Invalid token'})
                  }

              route53 = boto3.client('route53')
              record_name = os.environ['RECORD_NAME']
              zone_id = os.environ['HOSTED_ZONE_ID']

              # Get current IP from Route 53
              try:
                  resp = route53.list_resource_record_sets(
                      HostedZoneId=zone_id,
                      StartRecordName=record_name,
                      StartRecordType='A',
                      MaxItems='1'
                  )
                  records = resp.get('ResourceRecordSets', [])
                  current_ip = None
                  if records and records[0]['Name'].rstrip('.') == record_name.rstrip('.'):
                      current_ip = records[0]['ResourceRecords'][0]['Value']
              except Exception:
                  current_ip = None

              # Skip update if IP unchanged
              if current_ip == source_ip:
                  return {
                      'statusCode': 200,
                      'body': json.dumps({'message': 'No change', 'ip': source_ip})
                  }

              # Update Route 53
              try:
                  route53.change_resource_record_sets(
                      HostedZoneId=zone_id,
                      ChangeBatch={
                          'Changes': [{
                              'Action': 'UPSERT',
                              'ResourceRecordSet': {
                                  'Name': record_name,
                                  'Type': 'A',
                                  'TTL': 300,
                                  'ResourceRecords': [{'Value': source_ip}]
                              }
                          }]
                      }
                  )
                  print(f"IP_CHANGED old={current_ip} new={source_ip}")
              except Exception as e:
                  print(f"UPDATE_FAILED ip={source_ip} error={e}")
                  return {
                      'statusCode': 500,
                      'body': json.dumps({'error': 'DNS update failed'})
                  }

              return {
                  'statusCode': 200,
                  'body': json.dumps({
                      'message': 'DNS updated',
                      'record': record_name,
                      'ip': source_ip
                  })
              }

  # Log group with short retention
  UpdateFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-updater'
      RetentionInDays: 7
      Tags:
        - Key: Project
          Value: aws-easy
        - Key: Template
          Value: dynamic-dns

  # IAM role for Lambda
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Project
          Value: aws-easy
        - Key: Template
          Value: dynamic-dns
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: UpdateDNS
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: UpdateRoute53
                Effect: Allow
                Action:
                  - route53:ChangeResourceRecordSets
                  - route53:ListResourceRecordSets
                Resource: !Sub
                  - 'arn:aws:route53:::hostedzone/${ZoneId}'
                  - ZoneId: !GetAtt Setup.ZoneId
              - Sid: WriteLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  # API Gateway HTTP API
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${AWS::StackName}-api'
      ProtocolType: HTTP
      Tags:
        Project: aws-easy
        Template: dynamic-dns

  # API Gateway stage
  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true

  # API Gateway route
  HttpApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /update/{token}'
      Target: !Sub 'integrations/${HttpApiIntegration}'

  # API Gateway integration with Lambda
  HttpApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt UpdateFunction.Arn
      PayloadFormatVersion: '2.0'

  # Permission for API Gateway to invoke Lambda
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UpdateFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*'

Outputs:
  UpdateUrl:
    Description: Your update URL (keep this secret!)
    Value: !Sub
      - 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/update/${Token}'
      - Token: !GetAtt Setup.Token

  CronCommand:
    Description: Add this line to your crontab to update every 5 minutes
    Value: !Sub
      - '*/5 * * * * curl -s "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/update/${Token}"'
      - Token: !GetAtt Setup.Token

  RecordName:
    Description: DNS record being updated
    Value: !Ref RecordName
