AWSTemplateFormatVersion: '2010-09-09'
Description: Static website hosting with S3 and CloudFront

Parameters:
  DomainName:
    Type: String
    Default: ''
    Description: Optional custom domain name (e.g., example.com)

Conditions:
  HasDomain: !Not [!Equals [!Ref DomainName, '']]

Resources:
  # Cleanup function to empty bucket on stack deletion
  CleanupFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-cleanup'
      Runtime: python3.12
      Handler: index.handler
      Timeout: 300
      Role: !GetAtt CleanupRole.Arn
      Tags:
        - Key: Project
          Value: aws-easy
        - Key: Template
          Value: static-website
      Code:
        ZipFile: |
          import boto3
          import cfnresponse

          def handler(event, context):
              if event['RequestType'] != 'Delete':
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                  return

              bucket = event['ResourceProperties']['BucketName']
              s3 = boto3.resource('s3')

              try:
                  s3.Bucket(bucket).objects.all().delete()
                  s3.Bucket(bucket).object_versions.all().delete()
              except Exception as e:
                  print(f'Error emptying bucket: {e}')

              cfnresponse.send(event, context, cfnresponse.SUCCESS, {})

  CleanupRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Project
          Value: aws-easy
        - Key: Template
          Value: static-website
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: EmptyBucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                  - s3:ListBucket
                  - s3:ListBucketVersions
                Resource:
                  - !Sub 'arn:aws:s3:::${WebsiteBucket}'
                  - !Sub 'arn:aws:s3:::${WebsiteBucket}/*'

  BucketCleanup:
    Type: Custom::BucketCleanup
    Properties:
      ServiceToken: !GetAtt CleanupFunction.Arn
      BucketName: !Ref WebsiteBucket

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Project
          Value: aws-easy
        - Key: Template
          Value: static-website
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${WebsiteBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${AWS::StackName}-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      Tags:
        - Key: Project
          Value: aws-easy
        - Key: Template
          Value: static-website
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html
            ErrorCachingMinTTL: 60
        PriceClass: PriceClass_100
        HttpVersion: http2

Outputs:
  WebsiteURL:
    Description: Your website URL
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'

  BucketName:
    Description: S3 bucket for your website files
    Value: !Ref WebsiteBucket

  DistributionId:
    Description: CloudFront distribution ID (for cache invalidation)
    Value: !Ref CloudFrontDistribution
